Check if the merge needs to be redone. Do nothing if it's current.
Careful with the lookup in array of parent commit-ids.
we have to handle the failure ourselves & proceed to re-merging,
instead of failing & terminating the script.

diff --git a/bin/git-sum-branches b/bin/git-sum-branches
--- a/bin/git-sum-branches
+++ b/bin/git-sum-branches
@@ -87,6 +87,49 @@ first=$real_branches[1]
 
 others=($real_branches[2,-1])
 
+
+######################################## Test if up-to-date
+# take the branches' commit-ids
+# and parent-ids of the sum's head.
+# sort & compare
+commit_ids_summands=()
+foreach br ($summand_branches) {
+    commit_ids_summands+=$(git rev-parse $br)
+}
+commit_ids_sum_parents=($(git show -s --format=format:"%P" $sum_branch))
+
+equal=n
+if test ${#commit_ids_sum_parents} = ${#commit_ids_summands}
+then
+    equal=y
+    set +u # here we risk the "var. lookup" fails, so treat it explicitly
+    # here the O(N^2) tests:
+    foreach id ($commit_ids_summands) {
+	if ! [[ ${commit_ids_sum_parents[(r)$id]} = $id ]] ; then
+	    # if I had commit_ids_summands a hash, I could report
+	    # the symbolic name!
+	    cecho red "This one is not parent of the merge $id" >&2
+	    equal=n
+	else
+	    # cecho green "found $id" >&2
+	    :
+	fi
+    }
+    set -u # here again we don't (intend to) risk it.
+else
+    cecho red "different number of summands: " \
+	"${#commit_ids_sum_parents} != ${#commit_ids_summands}" >&2
+fi
+
+if test "$equal" = y;
+then
+    echo "no need to merge again -- the sum is up-to-date (as defined)." >&2
+    exit 0
+fi
+
+
+####################################### Merge
+
 if [ $reset = "y" ]; then
     #eval $cmd git checkout $sum_branch
     eval $cmd git checkout $first
