git-rebase-origin: fix the status test

diff --git a/bin/git-rebase-origin b/bin/git-rebase-origin
--- a/bin/git-rebase-origin
+++ b/bin/git-rebase-origin
@@ -92,10 +92,11 @@ then
 else
     ignore_options=()
 fi
+
 bases=($(git-walk-down $ignore_options -r $top|- grep segment| cut -f 3))
-if [[ $$ != 0 ]]
+if [[ $? != 0 ]]
 then
-    die "cannot contiue"
+    die "cannot continue -- git-walk-down failed"
 fi
 
 DEBUG "bases: $bases"
