rebase-poset: report the sum/segment which failed during rebase.

diff --git a/bin/git-rebase-poset b/bin/git-rebase-poset
--- a/bin/git-rebase-poset
+++ b/bin/git-rebase-poset
@@ -2,6 +2,14 @@
 
 foreach ref ($(git-tsort))
 {
-    git-rebase-ref $ref
+    # todo: create a tag, so that if `git-rebase' fails
+    # at least I see the segment (in gitk).
+    #
+    if ! git-rebase-ref $ref;
+    then
+	problem=$?
+	cecho red "Failure on $ref"
+	exit $problem
+    fi
 }
 
