Explain the error due to unexpected option or missing argument

diff --git a/bin/git-diff-segments b/bin/git-diff-segments
--- a/bin/git-diff-segments
+++ b/bin/git-diff-segments
@@ -37,6 +37,7 @@ while getopts :hv OPT; do
             verbose=y
             ;;
         *)
+            echo "unexpected option $OPT">&2
             usage >&2
             exit 2
     esac
@@ -46,6 +47,7 @@ OPTIND=1
 
 
 if [[ $# -lt 3 ]]; then
+    echo "missing arguments">&2
     usage >&2
     exit 1
 fi
diff --git a/bin/git-range-diff-segments b/bin/git-range-diff-segments
--- a/bin/git-range-diff-segments
+++ b/bin/git-range-diff-segments
@@ -18,6 +18,7 @@ while getopts :h OPT; do
             exit 0
             ;;
         *)
+            echo "unexpected option $OPT">&2
             usage >&2
             exit 2
     esac
@@ -26,6 +27,7 @@ shift OPTIND-1
 OPTIND=1
 
 if [[ $# -lt 2 ]]; then
+    echo "missing arguments">&2
     usage >&2
     exit 1
 fi
diff --git a/bin/git-reapply-segment b/bin/git-reapply-segment
--- a/bin/git-reapply-segment
+++ b/bin/git-reapply-segment
@@ -48,6 +48,7 @@ while getopts :b:hkn OPT; do
             # shift
             ;;
         *)
+            echo "unexpected option $OPT">&2
             usage >&2
             exit 2
     esac
@@ -56,6 +57,7 @@ shift OPTIND-1
 OPTIND=1
 
 if [ $# -lt 2 ]; then
+    echo "missing arguments">&2
     usage >&2
     exit 1
 fi
diff --git a/bin/git-rename b/bin/git-rename
--- a/bin/git-rename
+++ b/bin/git-rename
@@ -15,6 +15,7 @@ while getopts :h OPT; do
             exit 0
             ;;
         *)
+            echo "unexpected option $OPT">&2
             usage >&2
             exit 2
     esac
@@ -24,7 +25,8 @@ OPTIND=1
 
 if [ ! $# = 2 ];
 then
-    usage
+    echo "missing arguments">&2
+    usage>&2
     exit 1
 fi
 
diff --git a/bin/git-segment-patches b/bin/git-segment-patches
--- a/bin/git-segment-patches
+++ b/bin/git-segment-patches
@@ -38,7 +38,8 @@ while getopts :ho:pq OPT; do
             output_dir=$OPTARG
             ;;
         *)
-            usage
+            echo "unexpected option $OPT">&2
+            usage>&2
             exit 2
     esac
 done
@@ -47,7 +48,8 @@ OPTIND=1
 
 
 if [ $# -lt 1 ]; then
-    usage
+    echo "missing arguments">&2
+    usage>&2
     exit 2
 fi
 
diff --git a/bin/git-segment-split b/bin/git-segment-split
--- a/bin/git-segment-split
+++ b/bin/git-segment-split
@@ -29,6 +29,7 @@ while getopts :bh OPT; do
             ;;
         *)
             # wrong option
+            echo "unexpected option $OPT">&2
             usage >&2
             exit 1
     esac
@@ -38,6 +39,7 @@ OPTIND=1
 
 
 if [[ $# != 3 ]]; then
+    echo "missing arguments">&2
     usage >&2
     exit 1
 fi
diff --git a/bin/git-segments-balance b/bin/git-segments-balance
--- a/bin/git-segments-balance
+++ b/bin/git-segments-balance
@@ -24,6 +24,7 @@ while getopts :v OPT; do
             exit 0
             ;;
         *)
+            echo "unexpected option $OPT">&2
             usage >&2
             exit 2
     esac
@@ -32,6 +33,7 @@ shift OPTIND-1
 OPTIND=1
 
 if [[ $# != 3 ]]; then
+    echo "missing arguments">&2
     usage >&2
     exit 1
 fi
diff --git a/bin/git-shift-border b/bin/git-shift-border
--- a/bin/git-shift-border
+++ b/bin/git-shift-border
@@ -23,6 +23,7 @@ while getopts :h OPT; do
             exit 0
             ;;
         *)
+            echo "unexpected option $OPT">&2
             usage>&2
             exit 2
     esac
@@ -31,6 +32,7 @@ shift OPTIND-1
 OPTIND=1
 
 if [[ $# -lt 3 ]]; then
+    echo "missing arguments">&2
     usage >&2
     exit 1
 fi
diff --git a/bin/git-sum b/bin/git-sum
--- a/bin/git-sum
+++ b/bin/git-sum
@@ -157,7 +157,8 @@ while getopts :cdhnrs: OPT; do
             delete="y"
             ;;
         *)
-            usage
+            echo "unexpected option $OPT">&2
+            usage>&2
             exit 2
     esac
 done
@@ -165,6 +166,7 @@ shift $(( OPTIND - 1 ))
 OPTIND=1
 
 if [ $# -lt 1 ]; then
+    echo "missing arguments">&2
     usage
     exit -1
 fi
diff --git a/bin/git-sum-branches b/bin/git-sum-branches
--- a/bin/git-sum-branches
+++ b/bin/git-sum-branches
@@ -73,14 +73,16 @@ while (( $# > 0 )); do
             break
         ;;
         *)
-            usage
+            echo "unexpected option $OPT">&2
+            usage>&2
             exit 2
     esac
     shift
 done
 
 if [ $# != 1 ]; then
-    usage
+    echo "missing arguments">&2
+    usage>&2
     exit 1
 fi
 
diff --git a/bin/gitk-poset b/bin/gitk-poset
--- a/bin/gitk-poset
+++ b/bin/gitk-poset
@@ -49,6 +49,7 @@ while getopts :fgi:v OPT; do
             verbose=y
             ;;
         *)
+            echo "unexpected option $OPT">&2
             usage >&2
             exit 2
     esac
@@ -114,6 +115,7 @@ fi
 
 # only 1?
 if [ $# -gt 1 ]; then
+    echo "missing arguments">&2
     usage >&2
     exit 1
 elif [ $# = 0 ]; then
