verbosity in git-rebase for the hooks.

diff --git a/patches/git-rebase b/patches/git-rebase
--- a/patches/git-rebase
+++ b/patches/git-rebase
@@ -51,7 +51,7 @@ LF='
 '
 ok_to_skip_pre_rebase=
 resolvemsg="
-$(gettext 'When you have resolved this problem, run "git rebase --continue".
+$(gettext 'When you have RESOLVED this problem, run "git rebase --continue".
 If you prefer to skip this patch, run "git rebase --skip" instead.
 To check out the original branch and stop rebasing, run "git rebase --abort".')
 "
@@ -148,6 +148,7 @@ move_to_original_branch () {
 }
 
 finish_rebase () {
+    echo "finish_rebase" >&2
 	if test -x "$GIT_DIR/hooks/post-rebase"
 	then
 		"$GIT_DIR/hooks/post-rebase" ${1+"$@"}
@@ -173,6 +174,7 @@ You can run "git stash pop" or "git stash drop" at any time.
 }
 
 run_specific_rebase_internal () {
+    echo run_specific_rebase_internal >&2
 	if [ "$interactive_rebase" = implied ]; then
 		GIT_EDITOR=:
 		export GIT_EDITOR
@@ -194,6 +196,8 @@ run_specific_rebase () {
 	        cecho hiblue "calling finish_rebase to commit" >&2
 		# git-reset-segment name
 		finish_rebase
+	else
+	        echo "rebase failed. State has been saved." >&2
 	fi
 	exit $ret
 }
diff --git a/patches/git-rebase--am b/patches/git-rebase--am
--- a/patches/git-rebase--am
+++ b/patches/git-rebase--am
@@ -60,14 +60,16 @@ else
 		return $?
 	fi
 
+	echo "mmmmmmmmmmmmmmmmmmmmmmm" >&2
 	git am $git_am_opt --rebasing --resolvemsg="$resolvemsg" <"$GIT_DIR/rebased-patches"
 	ret=$?
-
+	set -x
 	rm -f "$GIT_DIR/rebased-patches"
 fi
 
 if test 0 != $ret
 then
+    echo "rebase failed" >&2
 	test -d "$state_dir" && write_basic_state
 	return $ret
 fi
