Less verbosity in git-rebase patch

diff --git a/patches/git-rebase--am b/patches/git-rebase--am
--- a/patches/git-rebase--am
+++ b/patches/git-rebase--am
@@ -67,7 +67,7 @@ fi
 
 if test 0 != $ret
 then
-    echo "rebase failed" >&2
+        echo "rebase failed" >&2
 	test -d "$state_dir" && write_basic_state
 	return $ret
 fi
